apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: db-zone
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
