apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: app-zone
spec:
  replicas: {{ .Values.springApp.replicas }}
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: {{ .Values.springApp.image }}
          ports:
            - containerPort: {{ .Values.springApp.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.db-zone.svc.cluster.local:5432/{{ .Values.postgres.database }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.user }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE
              value: {{ .Values.postgres.timezone }}
