apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: app-zone
spec:
  selector:
    app: spring-app
  ports:
    - port: {{ .Values.springApp.port }}
      targetPort: {{ .Values.springApp.port }}
  type: LoadBalancer
